name: Tahoma2D macOS Build

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          ci-scripts/osx/tahoma-install.sh
          brew install ccache
          mkdir /Users/runner/.ccache
      - uses: actions/cache@v2
        with:
          path: |
            /Users/runner/.ccache
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/aom
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/ffmpeg
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/opencv
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      - name: Get CanonSDK
        run: |
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" --header="Accept:application/octet-stream" -O EDSDK_v131231_Macintosh.zip https://api.github.com/repos/tahoma2d/CanonSDK/releases/assets/25267390
          unzip EDSDK_v131231_Macintosh.zip -d EDSDK_v131231_Macintosh
          unzip EDSDK_v131231_Macintosh/Macintosh.dmg.zip -d EDSDK_v131231_Macintosh
          7z x EDSDK_v131231_Macintosh/Macintosh.dmg -oEDSDK_v131231_Macintosh
          mv EDSDK_v131231_Macintosh/Macintosh/EDSDK/* thirdparty/canon
      - name: Get 3rd Party Apps
        run: |
          ci-scripts/osx/tahoma-get3rdpartyapps.sh
      - name: Build ffmpeg
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-buildffmpeg.sh
      - name: Build OpenCV
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-buildopencv.sh
      - name: Build Tahoma2D
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-build.sh
      - name: Create Package
        run: bash ./ci-scripts/osx/tahoma-buildpkg.sh
      - uses: actions/upload-artifact@v1
        with:
          name: Tahoma2D-osx.dmg
          path: toonz/build/Tahoma2D-osx.dmg
